=== KamilPabin/TechnologieXml/src/main/resources/students-grades.dtd
<!ELEMENT students (student)*>
        <!ELEMENT student (firstName|lastName|subjects|behaviour)*>
        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT subjects (subject)*>
        <!ELEMENT subject (name|grade)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT grade (#PCDATA)>
        <!ELEMENT behaviour (#PCDATA)>

=== KamilPabin/TechnologieXml/src/main/resources/students-grades.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="diploma.xslt"?>
<!DOCTYPE students SYSTEM "students-grades.dtd">
<students>
    <student>
        <firstName>Jan</firstName>
        <lastName>Nowak</lastName>
        <birthDate>02.04.1995</birthDate>
        <birthPlace>Poznań</birthPlace>
        <pesel>95040291857</pesel>
        <subjects>
            <subject>
                <name>physics</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>mathematics</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>biology</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>chemistry</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>technology</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>history</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>sport</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>geography</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>behaviour</name>
                <grade>Bardzo dobre</grade>
            </subject>
        </subjects>
        <mean>4.75</mean>
    </student>
    <student>
        <firstName>Adam</firstName>
        <lastName>Kowalski</lastName>
        <birthDate>11.09.1995</birthDate>
        <birthPlace>Poznań</birthPlace>
        <pesel>95091112983</pesel>
        <subjects>
            <subject>
                <name>physics</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>mathematics</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>biology</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>chemistry</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>technology</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>history</name>
                <grade>Dostateczny</grade>
            </subject>
            <subject>
                <name>sport</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>geography</name>
                <grade>Dobry</grade>
            </subject>
            <subject>
                <name>behaviour</name>
                <grade>Bardzo dobre</grade>
            </subject>
        </subjects>
        <mean>4.25</mean>
    </student>
    <student>
        <firstName>Maurycy</firstName>
        <lastName>Wójcik</lastName>
        <birthDate>24.07.1995</birthDate>
        <birthPlace>Swarzędz</birthPlace>
        <pesel>95072446873</pesel>
        <subjects>
            <subject>
                <name>physics</name>
                <grade>Dostateczny</grade>
            </subject>
            <subject>
                <name>mathematics</name>
                <grade>Dostateczny</grade>
            </subject>
            <subject>
                <name>biology</name>
                <grade>Dopuszczający</grade>
            </subject>
            <subject>
                <name>chemistry</name>
                <grade>Dopuszczający</grade>
            </subject>
            <subject>
                <name>technology</name>
                <grade>Dostateczny</grade>
            </subject>
            <subject>
                <name>history</name>
                <grade>Niedostateczny</grade>
            </subject>
            <subject>
                <name>sport</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>geography</name>
                <grade>Dopuszczający</grade>
            </subject>
            <subject>
                <name>behaviour</name>
                <grade>Poprawne</grade>
            </subject>
        </subjects>
        <mean>2.625</mean>
    </student>
    <student>
        <firstName>Joanna</firstName>
        <lastName>Wiśniewska</lastName>
        <birthDate>01.01.1995</birthDate>
        <birthPlace>Oborniki</birthPlace>
        <pesel>95010137104</pesel>
        <subjects>
            <subject>
                <name>physics</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>mathematics</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>biology</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>chemistry</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>technology</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>history</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>sport</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>geography</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>behaviour</name>
                <grade>Wzorowe</grade>
            </subject>
        </subjects>
        <mean>5.5</mean>
    </student>
    <student>
        <firstName>Karolina</firstName>
        <lastName>Kamińska</lastName>
        <birthDate>18.11.1995</birthDate>
        <birthPlace>Poznań</birthPlace>
        <pesel>95111836294</pesel>
        <subjects>
            <subject>
                <name>physics</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>mathematics</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>biology</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>chemistry</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>technology</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>history</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>sport</name>
                <grade>Bardzo dobry</grade>
            </subject>
            <subject>
                <name>geography</name>
                <grade>Celujący</grade>
            </subject>
            <subject>
                <name>behaviour</name>
                <grade>Wzorowe</grade>
            </subject>
        </subjects>
        <mean>5.5</mean>
    </student>
</students>
